name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout repository
        uses: actions/checkout@v3

      - name: 📂 Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ftpupload.net
          username: ${{ if0_38225053 }}
          password: ${{ nvGsFNwP4ITGL }}
          local-dir: ./
          server-dir: /htdocs/
